---

- name: Configuring
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart redis-server
  with_items:
    - "etc/redis/redis.conf"
